Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@cemmertsimsek 
cemmertsimsek
/
cemmertsimsek
Public
Code
Issues
Pull requests
Actions
Projects
Security
Insights
cemmertsimsek/.github/workflows/main.yml
@cemmertsimsek
eagrundy Create main.yml
Latest commit 8b08c94 on Jun 11, 2021
 History
 1 contributor
23 lines (22 sloc)  581 Bytes

name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
  
        with:
          github_user_name: cemmertsimsek
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
cemmertsimsek/main.yml at main · cemmertsimsek/cemmertsimsek
